"""initial_schema

Revision ID: 9aa5ce66b1ce
Revises: 
Create Date: 2026-05-15 21:24:25.967994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa5ce66b1ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=True),
    sa.Column('gewerk_scope', sa.JSON(), nullable=False),
    sa.Column('fuzzy_threshold', sa.Integer(), nullable=False),
    sa.Column('synonyms_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('extract', 'match', 'diff', 'report', name='tasktype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('result_path', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.Enum('pdf_vector', 'pdf_scan', 'dxf', 'dwg', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('plan_type', sa.Enum('schema', 'grundriss', name='plantype', native_enum=False), nullable=False),
    sa.Column('gewerk', sa.Enum('HLK', 'ELT', 'SAN', name='gewerk', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_project_id'), ['project_id'], unique=False)

    op.create_table('anlagen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.Enum('schema', 'grundriss', name='plantype', native_enum=False), nullable=False),
    sa.Column('gewerk', sa.Enum('HLK', 'ELT', 'SAN', name='gewerk', native_enum=False), nullable=False),
    sa.Column('label_raw', sa.String(length=512), nullable=False),
    sa.Column('label_normalized', sa.String(length=512), nullable=False),
    sa.Column('anlagentyp', sa.String(length=128), nullable=True),
    sa.Column('room_code', sa.String(length=64), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('aks', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anlagen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anlagen_label_normalized'), ['label_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_anlagen_plan_type'), ['plan_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_anlagen_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anlagen_room_code'), ['room_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_anlagen_upload_id'), ['upload_id'], unique=False)

    op.create_table('diff_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('diff_type', sa.Enum('only_schema', 'only_grundriss', 'attr_mismatch', 'room_mismatch', name='difftype', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='severity', native_enum=False), nullable=False),
    sa.Column('anlage_ref_id', sa.Integer(), nullable=True),
    sa.Column('partner_ref_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['anlage_ref_id'], ['anlagen.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_ref_id'], ['anlagen.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diff_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diff_entries_anlage_ref_id'), ['anlage_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diff_entries_diff_type'), ['diff_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_diff_entries_project_id'), ['project_id'], unique=False)

    op.create_table('match_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('schema_anlage_id', sa.Integer(), nullable=False),
    sa.Column('grundriss_anlage_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('auto', 'confirmed', 'rejected', 'manual', name='matchstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grundriss_anlage_id'], ['anlagen.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schema_anlage_id'], ['anlagen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_pairs_grundriss_anlage_id'), ['grundriss_anlage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_pairs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_pairs_schema_anlage_id'), ['schema_anlage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_pairs_schema_anlage_id'))
        batch_op.drop_index(batch_op.f('ix_match_pairs_project_id'))
        batch_op.drop_index(batch_op.f('ix_match_pairs_grundriss_anlage_id'))

    op.drop_table('match_pairs')
    with op.batch_alter_table('diff_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diff_entries_project_id'))
        batch_op.drop_index(batch_op.f('ix_diff_entries_diff_type'))
        batch_op.drop_index(batch_op.f('ix_diff_entries_anlage_ref_id'))

    op.drop_table('diff_entries')
    with op.batch_alter_table('anlagen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anlagen_upload_id'))
        batch_op.drop_index(batch_op.f('ix_anlagen_room_code'))
        batch_op.drop_index(batch_op.f('ix_anlagen_project_id'))
        batch_op.drop_index(batch_op.f('ix_anlagen_plan_type'))
        batch_op.drop_index(batch_op.f('ix_anlagen_label_normalized'))

    op.drop_table('anlagen')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_project_id'))

    op.drop_table('uploads')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))

    op.drop_table('tasks')
    op.drop_table('projects')
    # ### end Alembic commands ###
